/**
 * generated by Xtext 2.17.0.M1
 */
package lu.snt.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>for Allformula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.snt.socrates.forAllformula#getBound <em>Bound</em>}</li>
 *   <li>{@link lu.snt.socrates.forAllformula#getForallchild <em>Forallchild</em>}</li>
 * </ul>
 *
 * @see lu.snt.socrates.SocratesPackage#getforAllformula()
 * @model
 * @generated
 */
public interface forAllformula extends EObject
{
  /**
   * Returns the value of the '<em><b>Bound</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bound</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bound</em>' containment reference.
   * @see #setBound(boundterm)
   * @see lu.snt.socrates.SocratesPackage#getforAllformula_Bound()
   * @model containment="true"
   * @generated
   */
  boundterm getBound();

  /**
   * Sets the value of the '{@link lu.snt.socrates.forAllformula#getBound <em>Bound</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bound</em>' containment reference.
   * @see #getBound()
   * @generated
   */
  void setBound(boundterm value);

  /**
   * Returns the value of the '<em><b>Forallchild</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Forallchild</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forallchild</em>' containment reference.
   * @see #setForallchild(formula)
   * @see lu.snt.socrates.SocratesPackage#getforAllformula_Forallchild()
   * @model containment="true"
   * @generated
   */
  formula getForallchild();

  /**
   * Sets the value of the '{@link lu.snt.socrates.forAllformula#getForallchild <em>Forallchild</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forallchild</em>' containment reference.
   * @see #getForallchild()
   * @generated
   */
  void setForallchild(formula value);

} // forAllformula
