/**
 * generated by Xtext 2.17.0.M1
 */
package lu.snt.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>formulab</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.snt.socrates.formulab#getA <em>A</em>}</li>
 *   <li>{@link lu.snt.socrates.formulab#getT <em>T</em>}</li>
 * </ul>
 *
 * @see lu.snt.socrates.SocratesPackage#getformulab()
 * @model
 * @generated
 */
public interface formulab extends EObject
{
  /**
   * Returns the value of the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>A</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>A</em>' containment reference.
   * @see #setA(term)
   * @see lu.snt.socrates.SocratesPackage#getformulab_A()
   * @model containment="true"
   * @generated
   */
  term getA();

  /**
   * Sets the value of the '{@link lu.snt.socrates.formulab#getA <em>A</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A</em>' containment reference.
   * @see #getA()
   * @generated
   */
  void setA(term value);

  /**
   * Returns the value of the '<em><b>T</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>T</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' containment reference.
   * @see #setT(formulabprime)
   * @see lu.snt.socrates.SocratesPackage#getformulab_T()
   * @model containment="true"
   * @generated
   */
  formulabprime getT();

  /**
   * Sets the value of the '{@link lu.snt.socrates.formulab#getT <em>T</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' containment reference.
   * @see #getT()
   * @generated
   */
  void setT(formulabprime value);

} // formulab
