/**
 * generated by Xtext 2.17.0.M1
 */
package lu.snt.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>negationformula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.snt.socrates.negationformula#getNegationchild <em>Negationchild</em>}</li>
 * </ul>
 *
 * @see lu.snt.socrates.SocratesPackage#getnegationformula()
 * @model
 * @generated
 */
public interface negationformula extends EObject
{
  /**
   * Returns the value of the '<em><b>Negationchild</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Negationchild</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negationchild</em>' containment reference.
   * @see #setNegationchild(formula)
   * @see lu.snt.socrates.SocratesPackage#getnegationformula_Negationchild()
   * @model containment="true"
   * @generated
   */
  formula getNegationchild();

  /**
   * Sets the value of the '{@link lu.snt.socrates.negationformula#getNegationchild <em>Negationchild</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Negationchild</em>' containment reference.
   * @see #getNegationchild()
   * @generated
   */
  void setNegationchild(formula value);

} // negationformula
