/*
 * generated by Xtext 2.19.0
 */
package lu.uni.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSocratesScopeProvider extends DelegatingScopeProvider {
}
