/*
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSocratesScopeProvider extends DelegatingScopeProvider {
}
