/**
 * generated by Xtext 2.10.0
 */
package lu.snt.ui;

import lu.snt.ui.AbstractSocratesUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SocratesUiModule extends AbstractSocratesUiModule {
  public SocratesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
