/**
 * generated by Xtext 2.16.0
 */
package lu.snt.ide;

import lu.snt.ide.AbstractSocratesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SocratesIdeModule extends AbstractSocratesIdeModule {
}
