/**
 * generated by Xtext 2.17.0.M1
 */
package lu.snt.socrates.impl;

import lu.snt.socrates.SocratesPackage;
import lu.snt.socrates.expressionterm;
import lu.snt.socrates.expressiontermprime;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>expressionterm</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link lu.snt.socrates.impl.expressiontermImpl#getTerm <em>Term</em>}</li>
 *   <li>{@link lu.snt.socrates.impl.expressiontermImpl#getExpprime <em>Expprime</em>}</li>
 * </ul>
 *
 * @generated
 */
public class expressiontermImpl extends MinimalEObjectImpl.Container implements expressionterm
{
  /**
   * The cached value of the '{@link #getTerm() <em>Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerm()
   * @generated
   * @ordered
   */
  protected EObject term;

  /**
   * The cached value of the '{@link #getExpprime() <em>Expprime</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpprime()
   * @generated
   * @ordered
   */
  protected expressiontermprime expprime;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected expressiontermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SocratesPackage.Literals.EXPRESSIONTERM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getTerm()
  {
    return term;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTerm(EObject newTerm, NotificationChain msgs)
  {
    EObject oldTerm = term;
    term = newTerm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SocratesPackage.EXPRESSIONTERM__TERM, oldTerm, newTerm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTerm(EObject newTerm)
  {
    if (newTerm != term)
    {
      NotificationChain msgs = null;
      if (term != null)
        msgs = ((InternalEObject)term).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SocratesPackage.EXPRESSIONTERM__TERM, null, msgs);
      if (newTerm != null)
        msgs = ((InternalEObject)newTerm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SocratesPackage.EXPRESSIONTERM__TERM, null, msgs);
      msgs = basicSetTerm(newTerm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SocratesPackage.EXPRESSIONTERM__TERM, newTerm, newTerm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public expressiontermprime getExpprime()
  {
    return expprime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpprime(expressiontermprime newExpprime, NotificationChain msgs)
  {
    expressiontermprime oldExpprime = expprime;
    expprime = newExpprime;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SocratesPackage.EXPRESSIONTERM__EXPPRIME, oldExpprime, newExpprime);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpprime(expressiontermprime newExpprime)
  {
    if (newExpprime != expprime)
    {
      NotificationChain msgs = null;
      if (expprime != null)
        msgs = ((InternalEObject)expprime).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SocratesPackage.EXPRESSIONTERM__EXPPRIME, null, msgs);
      if (newExpprime != null)
        msgs = ((InternalEObject)newExpprime).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SocratesPackage.EXPRESSIONTERM__EXPPRIME, null, msgs);
      msgs = basicSetExpprime(newExpprime, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SocratesPackage.EXPRESSIONTERM__EXPPRIME, newExpprime, newExpprime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SocratesPackage.EXPRESSIONTERM__TERM:
        return basicSetTerm(null, msgs);
      case SocratesPackage.EXPRESSIONTERM__EXPPRIME:
        return basicSetExpprime(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SocratesPackage.EXPRESSIONTERM__TERM:
        return getTerm();
      case SocratesPackage.EXPRESSIONTERM__EXPPRIME:
        return getExpprime();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SocratesPackage.EXPRESSIONTERM__TERM:
        setTerm((EObject)newValue);
        return;
      case SocratesPackage.EXPRESSIONTERM__EXPPRIME:
        setExpprime((expressiontermprime)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SocratesPackage.EXPRESSIONTERM__TERM:
        setTerm((EObject)null);
        return;
      case SocratesPackage.EXPRESSIONTERM__EXPPRIME:
        setExpprime((expressiontermprime)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SocratesPackage.EXPRESSIONTERM__TERM:
        return term != null;
      case SocratesPackage.EXPRESSIONTERM__EXPPRIME:
        return expprime != null;
    }
    return super.eIsSet(featureID);
  }

} //expressiontermImpl
