/*
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.ui.tests;

import com.google.inject.Injector;
import lu.uni.socrates.ui.internal.SocratesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SocratesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SocratesActivator.getInstance().getInjector("lu.uni.Socrates");
	}

}
