/*
 * generated by Xtext 2.17.0.M1
 */
package lu.uni


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SocratesStandaloneSetup extends SocratesStandaloneSetupGenerated {

	def static void doSetup() {
		new SocratesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
