/**
 * generated by Xtext 2.19.0
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>atom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.atom#getF <em>F</em>}</li>
 *   <li>{@link lu.uni.socrates.atom#getS1 <em>S1</em>}</li>
 *   <li>{@link lu.uni.socrates.atom#getOp <em>Op</em>}</li>
 *   <li>{@link lu.uni.socrates.atom#getS2 <em>S2</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getatom()
 * @model
 * @generated
 */
public interface atom extends EObject
{
  /**
   * Returns the value of the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' containment reference.
   * @see #setF(formula)
   * @see lu.uni.socrates.SocratesPackage#getatom_F()
   * @model containment="true"
   * @generated
   */
  formula getF();

  /**
   * Sets the value of the '{@link lu.uni.socrates.atom#getF <em>F</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' containment reference.
   * @see #getF()
   * @generated
   */
  void setF(formula value);

  /**
   * Returns the value of the '<em><b>S1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S1</em>' containment reference.
   * @see #setS1(expression)
   * @see lu.uni.socrates.SocratesPackage#getatom_S1()
   * @model containment="true"
   * @generated
   */
  expression getS1();

  /**
   * Sets the value of the '{@link lu.uni.socrates.atom#getS1 <em>S1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S1</em>' containment reference.
   * @see #getS1()
   * @generated
   */
  void setS1(expression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see lu.uni.socrates.SocratesPackage#getatom_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link lu.uni.socrates.atom#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>S2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S2</em>' containment reference.
   * @see #setS2(expression)
   * @see lu.uni.socrates.SocratesPackage#getatom_S2()
   * @model containment="true"
   * @generated
   */
  expression getS2();

  /**
   * Sets the value of the '{@link lu.uni.socrates.atom#getS2 <em>S2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S2</em>' containment reference.
   * @see #getS2()
   * @generated
   */
  void setS2(expression value);

} // atom
