/**
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>basicformulae</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.basicformulae#getF <em>F</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getbasicformulae()
 * @model
 * @generated
 */
public interface basicformulae extends EObject
{
  /**
   * Returns the value of the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' containment reference.
   * @see #setF(EObject)
   * @see lu.uni.socrates.SocratesPackage#getbasicformulae_F()
   * @model containment="true"
   * @generated
   */
  EObject getF();

  /**
   * Sets the value of the '{@link lu.uni.socrates.basicformulae#getF <em>F</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' containment reference.
   * @see #getF()
   * @generated
   */
  void setF(EObject value);

} // basicformulae
