/**
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.socrates;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constants Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.ConstantsDefinition#getConstants <em>Constants</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getConstantsDefinition()
 * @model
 * @generated
 */
public interface ConstantsDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Constants</b></em>' containment reference list.
   * The list contents are of type {@link lu.uni.socrates.ConstantDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constants</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constants</em>' containment reference list.
   * @see lu.uni.socrates.SocratesPackage#getConstantsDefinition_Constants()
   * @model containment="true"
   * @generated
   */
  EList<ConstantDefinition> getConstants();

} // ConstantsDefinition
