/**
 * generated by Xtext 2.19.0
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existsformula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.Existsformula#getBound <em>Bound</em>}</li>
 *   <li>{@link lu.uni.socrates.Existsformula#getExistschild <em>Existschild</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getExistsformula()
 * @model
 * @generated
 */
public interface Existsformula extends EObject
{
  /**
   * Returns the value of the '<em><b>Bound</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bound</em>' containment reference.
   * @see #setBound(boundterm)
   * @see lu.uni.socrates.SocratesPackage#getExistsformula_Bound()
   * @model containment="true"
   * @generated
   */
  boundterm getBound();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Existsformula#getBound <em>Bound</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bound</em>' containment reference.
   * @see #getBound()
   * @generated
   */
  void setBound(boundterm value);

  /**
   * Returns the value of the '<em><b>Existschild</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Existschild</em>' containment reference.
   * @see #setExistschild(formula)
   * @see lu.uni.socrates.SocratesPackage#getExistsformula_Existschild()
   * @model containment="true"
   * @generated
   */
  formula getExistschild();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Existsformula#getExistschild <em>Existschild</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Existschild</em>' containment reference.
   * @see #getExistschild()
   * @generated
   */
  void setExistschild(formula value);

} // Existsformula
