/**
 * generated by Xtext 2.19.0
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>expressionterm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.expressionterm#getTerm <em>Term</em>}</li>
 *   <li>{@link lu.uni.socrates.expressionterm#getExpprime <em>Expprime</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getexpressionterm()
 * @model
 * @generated
 */
public interface expressionterm extends EObject
{
  /**
   * Returns the value of the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' containment reference.
   * @see #setTerm(EObject)
   * @see lu.uni.socrates.SocratesPackage#getexpressionterm_Term()
   * @model containment="true"
   * @generated
   */
  EObject getTerm();

  /**
   * Sets the value of the '{@link lu.uni.socrates.expressionterm#getTerm <em>Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' containment reference.
   * @see #getTerm()
   * @generated
   */
  void setTerm(EObject value);

  /**
   * Returns the value of the '<em><b>Expprime</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expprime</em>' containment reference.
   * @see #setExpprime(expressiontermprime)
   * @see lu.uni.socrates.SocratesPackage#getexpressionterm_Expprime()
   * @model containment="true"
   * @generated
   */
  expressiontermprime getExpprime();

  /**
   * Sets the value of the '{@link lu.uni.socrates.expressionterm#getExpprime <em>Expprime</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expprime</em>' containment reference.
   * @see #getExpprime()
   * @generated
   */
  void setExpprime(expressiontermprime value);

} // expressionterm
