/**
 * generated by Xtext 2.19.0
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Allformula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.ForAllformula#getBound <em>Bound</em>}</li>
 *   <li>{@link lu.uni.socrates.ForAllformula#getForallchild <em>Forallchild</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getForAllformula()
 * @model
 * @generated
 */
public interface ForAllformula extends EObject
{
  /**
   * Returns the value of the '<em><b>Bound</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bound</em>' containment reference.
   * @see #setBound(boundterm)
   * @see lu.uni.socrates.SocratesPackage#getForAllformula_Bound()
   * @model containment="true"
   * @generated
   */
  boundterm getBound();

  /**
   * Sets the value of the '{@link lu.uni.socrates.ForAllformula#getBound <em>Bound</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bound</em>' containment reference.
   * @see #getBound()
   * @generated
   */
  void setBound(boundterm value);

  /**
   * Returns the value of the '<em><b>Forallchild</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forallchild</em>' containment reference.
   * @see #setForallchild(formula)
   * @see lu.uni.socrates.SocratesPackage#getForAllformula_Forallchild()
   * @model containment="true"
   * @generated
   */
  formula getForallchild();

  /**
   * Sets the value of the '{@link lu.uni.socrates.ForAllformula#getForallchild <em>Forallchild</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forallchild</em>' containment reference.
   * @see #getForallchild()
   * @generated
   */
  void setForallchild(formula value);

} // ForAllformula
