/**
 * generated by Xtext 2.19.0
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Oracle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.Oracle#getModelName <em>Model Name</em>}</li>
 *   <li>{@link lu.uni.socrates.Oracle#getPath <em>Path</em>}</li>
 *   <li>{@link lu.uni.socrates.Oracle#getReqname <em>Reqname</em>}</li>
 *   <li>{@link lu.uni.socrates.Oracle#getSigndef <em>Signdef</em>}</li>
 *   <li>{@link lu.uni.socrates.Oracle#getConstantDefinitions <em>Constant Definitions</em>}</li>
 *   <li>{@link lu.uni.socrates.Oracle#getRequirement <em>Requirement</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getOracle()
 * @model
 * @generated
 */
public interface Oracle extends EObject
{
  /**
   * Returns the value of the '<em><b>Model Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model Name</em>' attribute.
   * @see #setModelName(String)
   * @see lu.uni.socrates.SocratesPackage#getOracle_ModelName()
   * @model
   * @generated
   */
  String getModelName();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Oracle#getModelName <em>Model Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model Name</em>' attribute.
   * @see #getModelName()
   * @generated
   */
  void setModelName(String value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see lu.uni.socrates.SocratesPackage#getOracle_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Oracle#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Reqname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reqname</em>' attribute.
   * @see #setReqname(String)
   * @see lu.uni.socrates.SocratesPackage#getOracle_Reqname()
   * @model
   * @generated
   */
  String getReqname();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Oracle#getReqname <em>Reqname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reqname</em>' attribute.
   * @see #getReqname()
   * @generated
   */
  void setReqname(String value);

  /**
   * Returns the value of the '<em><b>Signdef</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signdef</em>' containment reference.
   * @see #setSigndef(Signalsdefinition)
   * @see lu.uni.socrates.SocratesPackage#getOracle_Signdef()
   * @model containment="true"
   * @generated
   */
  Signalsdefinition getSigndef();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Oracle#getSigndef <em>Signdef</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signdef</em>' containment reference.
   * @see #getSigndef()
   * @generated
   */
  void setSigndef(Signalsdefinition value);

  /**
   * Returns the value of the '<em><b>Constant Definitions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant Definitions</em>' containment reference.
   * @see #setConstantDefinitions(ConstantsDefinition)
   * @see lu.uni.socrates.SocratesPackage#getOracle_ConstantDefinitions()
   * @model containment="true"
   * @generated
   */
  ConstantsDefinition getConstantDefinitions();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Oracle#getConstantDefinitions <em>Constant Definitions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant Definitions</em>' containment reference.
   * @see #getConstantDefinitions()
   * @generated
   */
  void setConstantDefinitions(ConstantsDefinition value);

  /**
   * Returns the value of the '<em><b>Requirement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirement</em>' containment reference.
   * @see #setRequirement(Requirement)
   * @see lu.uni.socrates.SocratesPackage#getOracle_Requirement()
   * @model containment="true"
   * @generated
   */
  Requirement getRequirement();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Oracle#getRequirement <em>Requirement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Requirement</em>' containment reference.
   * @see #getRequirement()
   * @generated
   */
  void setRequirement(Requirement value);

} // Oracle
