/**
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Signal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.Signal#getSignalid <em>Signalid</em>}</li>
 *   <li>{@link lu.uni.socrates.Signal#getTimdedterm <em>Timdedterm</em>}</li>
 *   <li>{@link lu.uni.socrates.Signal#getIndx1 <em>Indx1</em>}</li>
 *   <li>{@link lu.uni.socrates.Signal#getIndx2 <em>Indx2</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getSignal()
 * @model
 * @generated
 */
public interface Signal extends EObject
{
  /**
   * Returns the value of the '<em><b>Signalid</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Signalid</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signalid</em>' reference.
   * @see #setSignalid(SignalID)
   * @see lu.uni.socrates.SocratesPackage#getSignal_Signalid()
   * @model
   * @generated
   */
  SignalID getSignalid();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Signal#getSignalid <em>Signalid</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signalid</em>' reference.
   * @see #getSignalid()
   * @generated
   */
  void setSignalid(SignalID value);

  /**
   * Returns the value of the '<em><b>Timdedterm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Timdedterm</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timdedterm</em>' containment reference.
   * @see #setTimdedterm(timedterm)
   * @see lu.uni.socrates.SocratesPackage#getSignal_Timdedterm()
   * @model containment="true"
   * @generated
   */
  timedterm getTimdedterm();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Signal#getTimdedterm <em>Timdedterm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Timdedterm</em>' containment reference.
   * @see #getTimdedterm()
   * @generated
   */
  void setTimdedterm(timedterm value);

  /**
   * Returns the value of the '<em><b>Indx1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Indx1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indx1</em>' attribute.
   * @see #setIndx1(String)
   * @see lu.uni.socrates.SocratesPackage#getSignal_Indx1()
   * @model
   * @generated
   */
  String getIndx1();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Signal#getIndx1 <em>Indx1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Indx1</em>' attribute.
   * @see #getIndx1()
   * @generated
   */
  void setIndx1(String value);

  /**
   * Returns the value of the '<em><b>Indx2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Indx2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indx2</em>' attribute.
   * @see #setIndx2(String)
   * @see lu.uni.socrates.SocratesPackage#getSignal_Indx2()
   * @model
   * @generated
   */
  String getIndx2();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Signal#getIndx2 <em>Indx2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Indx2</em>' attribute.
   * @see #getIndx2()
   * @generated
   */
  void setIndx2(String value);

} // Signal
