/**
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.Sin#getExp1 <em>Exp1</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getSin()
 * @model
 * @generated
 */
public interface Sin extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp1</em>' containment reference.
   * @see #setExp1(expression)
   * @see lu.uni.socrates.SocratesPackage#getSin_Exp1()
   * @model containment="true"
   * @generated
   */
  expression getExp1();

  /**
   * Sets the value of the '{@link lu.uni.socrates.Sin#getExp1 <em>Exp1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp1</em>' containment reference.
   * @see #getExp1()
   * @generated
   */
  void setExp1(expression value);

} // Sin
