/**
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.socrates;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Socrates</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.Socrates#getOracles <em>Oracles</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#getSocrates()
 * @model
 * @generated
 */
public interface Socrates extends EObject
{
  /**
   * Returns the value of the '<em><b>Oracles</b></em>' containment reference list.
   * The list contents are of type {@link lu.uni.socrates.Oracle}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Oracles</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oracles</em>' containment reference list.
   * @see lu.uni.socrates.SocratesPackage#getSocrates_Oracles()
   * @model containment="true"
   * @generated
   */
  EList<Oracle> getOracles();

} // Socrates
