/**
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.socrates;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>timedterm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lu.uni.socrates.timedterm#getInf <em>Inf</em>}</li>
 *   <li>{@link lu.uni.socrates.timedterm#getNumber <em>Number</em>}</li>
 *   <li>{@link lu.uni.socrates.timedterm#getRef <em>Ref</em>}</li>
 *   <li>{@link lu.uni.socrates.timedterm#getOp <em>Op</em>}</li>
 *   <li>{@link lu.uni.socrates.timedterm#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see lu.uni.socrates.SocratesPackage#gettimedterm()
 * @model
 * @generated
 */
public interface timedterm extends EObject
{
  /**
   * Returns the value of the '<em><b>Inf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inf</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inf</em>' attribute.
   * @see #setInf(String)
   * @see lu.uni.socrates.SocratesPackage#gettimedterm_Inf()
   * @model
   * @generated
   */
  String getInf();

  /**
   * Sets the value of the '{@link lu.uni.socrates.timedterm#getInf <em>Inf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inf</em>' attribute.
   * @see #getInf()
   * @generated
   */
  void setInf(String value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(String)
   * @see lu.uni.socrates.SocratesPackage#gettimedterm_Number()
   * @model
   * @generated
   */
  String getNumber();

  /**
   * Sets the value of the '{@link lu.uni.socrates.timedterm#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(String value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(EObject)
   * @see lu.uni.socrates.SocratesPackage#gettimedterm_Ref()
   * @model
   * @generated
   */
  EObject getRef();

  /**
   * Sets the value of the '{@link lu.uni.socrates.timedterm#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(EObject value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see lu.uni.socrates.SocratesPackage#gettimedterm_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link lu.uni.socrates.timedterm#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(value)
   * @see lu.uni.socrates.SocratesPackage#gettimedterm_Value()
   * @model containment="true"
   * @generated
   */
  value getValue();

  /**
   * Sets the value of the '{@link lu.uni.socrates.timedterm#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(value value);

} // timedterm
