/*
 * generated by Xtext 2.17.0.M1
 */
package lu.uni.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class SocratesOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
